version: '3'

services:

#  api:
#    container_name: api
#    image: api
#    build:
#      context: ./
#      dockerfile: ./api/Dockerfile
#    restart: always
#    ports:
#      - "3000:3000"
#    networks:
#      - shoowscore
#    links:
#      - "mongo"

  mongo:
    container_name: mongo
    image: mongo:4.2.8-bionic
    restart: always
    ports:
      - "27017:27017"
    logging:
      driver: none
    networks:
      - shoowscore

  nginx:
    container_name: nginx
    image: nginx:1.19.1
    build:
      context: ./
      dockerfile: ./nginx/Dockerfile
    restart: always
    ports:
      - "80:80"
      - "443:443"
#    depends_on:
#      - api
    networks:
      - shoowscore

networks:
  shoowscore:
    driver: bridge
